=== barsanges/dt-protocole/schemas/etat.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "description": "Etat d'une partie de Dungeon Twister, vu par un arbitre omniscient",
    "type": "object",
    "properties":
    {
        "salles":
        {
            "description": "Les salles du labyrinthe",
            "type": "object",
            "additionalProperties":
            {
                "type": "object",
                "properties":
                {
                    "référence":
                    {
                        "$ref": "references/salles.schema.json"
                    },
                    "position":
                    {
                        "$ref": "position/position_salle.schema.json"
                    },
                    "la salle est cachée":
                    {
                        "type": "object",
                        "properties":
                        {
                            "la référence est connue de":
                            {
                                "type": "array",
                                "uniqueItems": true,
                                "items":
                                {
                                    "$ref": "references/joueurs.schema.json"
                                }
                            },
                            "l'orientation est connue de":
                            {
                                "type": "array",
                                "uniqueItems": true,
                                "items":
                                {
                                    "$ref": "references/joueurs.schema.json"
                                }
                            }
                        },
                        "required":
                        [
                            "la référence est connue de",
                            "l'orientation est connue de"
                        ]
                    }
                },
                "required": ["référence", "position"]
            }
        },
        "personnages":
        {
            "description": "Les personnage présents dans le labyrinthe",
            "type": "array",
            "items":
            {
                "type": "object",
                "properties":
                {
                    "couleur":
                    {
                        "$ref": "references/joueurs.schema.json"
                    },
                    "nature":
                    {
                        "$ref": "references/personnages.schema.json"
                    },
                    "emplacement":
                    {
                        "$ref": "position/position_case.schema.json"
                    },
                    "blessé":
                    {
                        "type": "boolean"
                    }
                },
                "required":
                [
                    "couleur",
                    "nature",
                    "emplacement",
                    "blessé"
                ]
            }
        },
        "objets":
        {
            "description": "Les objets présents dans le labyrinthe",
            "type": "array",
            "items":
            {
                "type": "object",
                "properties":
                {
                    "appartenance":
                    {
                        "$ref": "references/appartenances.schema.json"
                    },
                    "nature":
                    {
                        "$ref": "references/objets.schema.json"
                    },
                    "emplacement":
                    {
                        "$ref": "position/position_case.schema.json"
                    }
                },
                "required":
                [
                    "couleur",
                    "nature",
                    "emplacement"
                ]
            }
        },
        "cartes bleues":
        {
            "description": "Les cartes du joueur bleu (main et défausse)",
            "$ref": "cartes/paquet.schema.json"
        },
        "cartes jaunes":
        {
            "description": "Les cartes du joueur jaune (main et défausse)",
            "$ref": "cartes/paquet.schema.json"
        },
        "déroulé":
        {
            "description": "Les informations générales et communes sur le déroulé de la partie",
            "type": "object",
            "properties":
            {
                "scénario":
                {
                    "$ref": "references/scenarios.schema.json"
                },
                "joueur résolvant":
                {
                    "description": "Le joueur qui doit résoudre un effet, même s'il ne s'agit pas nécessairement du joueur actif (e.g. le joueur qui se défend dans un combat)",
                    "oneOf":
                    [
                        {
                            "$ref": "references/joueurs.schema.json"
                        },
                        {
                            "enum": [["bleu", "jaune"],
                                     ["jaune", "bleu"]]
                        }
                    ]
                },
                "joueur actif":
                {
                    "description": "Le joueur dont c'est le tour",
                    "$ref": "references/joueurs.schema.json"
                },
                "premier joueur":
                {
                    "description": "Le joueur qui a joué une carte action le premier",
                    "$ref": "references/joueurs.schema.json"
                },
                "tour":
                {
                    "type": "integer"
                },
                "actions restantes":
                {
                    "type": "integer",
                    "minimum": 0
                },
                "décision attendue":
                {
                    "$ref": "transitions/attendu.schema.json"
                }
            },
            "required":
            [
                "scénario",
                "joueur résolvant",
                "décision attendue"
            ]
        }
    },
    "required":
    [
        "salles",
        "personnages",
        "objets",
        "cartes bleues",
        "cartes jaunes",
        "déroulé"
    ]
}

=== barsanges/dt-protocole/validation/valides/passer-01/etat.json
{
    "salles":
    {
        "a":
        {
            "référence": [2, "anti-horaire"],
            "position":
            {
                "rotation":
                {
                    "matrice":  [[0, 1],
                                 [1, 0]],
                    "vecteur": [0, 0]
                },
                "translation": [0, 0]
            }
        }
    },
    "personnages":
    [
        {
            "couleur": "bleu",
            "nature": "Guerrier",
            "emplacement":
            {
                "salle": "a",
                "coordonnées": [0, 0]
            },
            "blessé": false
        },
        {
            "couleur": "jaune",
            "nature": "Passe-muraille",
            "emplacement":
            {
                "salle": "a",
                "coordonnées": [4, 4]
            },
            "blessé": false
        }
    ],
    "objets": [],
    "cartes bleues":
    {
        "main":
        {
            "cartes sauts": 3,
            "cartes actions": [3, 4, 5],
            "cartes de combat": [0, 1, 2, 2, 3, 3, 4, 5, 6]
        },
        "défausse":
        {
            "cartes sauts": 0,
            "cartes actions": [2],
            "cartes de combat": []
        }
    },
    "cartes jaunes":
    {
        "main":
        {
            "cartes sauts": 3,
            "cartes actions": [2, 3, 4, 5],
            "cartes de combat": [0, 1, 2, 2, 3, 3, 4, 5, 6]
        },
        "défausse":
        {
            "cartes sauts": 0,
            "cartes actions": [],
            "cartes de combat": []
        }
    },
    "déroulé":
    {
        "scénario": "exemple",
        "joueur résolvant": "bleu",
        "premier joueur": "bleu",
        "joueur actif": "bleu",
        "tour": 1,
        "actions restantes": 2,
        "décision attendue": "Choix d'une action"
    }
}

=== barsanges/dt-protocole/test/etat/etat-valide-01.json
{
    "salles":
    {},
    "personnages":
    [],
    "objets":
    [],
    "cartes bleues":
    {
        "main":
        {
            "cartes sauts": 3,
            "cartes actions": [2, 3, 4, 5],
            "cartes de combat": [0, 1, 2, 2, 3, 3, 4, 5, 6]
        },
        "défausse":
        {
            "cartes sauts": 0,
            "cartes actions": [],
            "cartes de combat": []
        }
    },
    "cartes jaunes":
    {
        "main":
        {
            "cartes sauts": 3,
            "cartes actions": [2, 3, 4, 5],
            "cartes de combat": [0, 1, 2, 2, 3, 3, 4, 5, 6]
        },
        "défausse":
        {
            "cartes sauts": 0,
            "cartes actions": [],
            "cartes de combat": []
        }
    },
    "déroulé":
    {
        "scénario": "standard",
        "joueur résolvant": "bleu",
        "décision attendue": "Choix d'une carte action"
    }
}
